import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import App from "@/components/app/App";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"dark"}>
        <App>{children}</App>
      </body>
    </html>
  );
}
